# -*- coding: utf-8 -*-
"""Inmersión-datos-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jqvXkwPA9vfmLIg6CohWJbHsWUsVsG19
"""

from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

inmuebles = pd.read_csv('inmuebles_bogota.csv')
inmuebles.head()

inmuebles.shape

inmuebles.columns

columnas = {'Baños':'Banos','Área':'Area'}
inmuebles = inmuebles.rename(columns=columnas)
inmuebles.sample(10)

inmuebles.info()

inmuebles.iloc[300:305]

print(type(inmuebles['Valor'][300:305]))

inmuebles.Area.mean()

inmuebles.sample(100)

(inmuebles.Barrio == 'Chico Reservado')

sum((inmuebles.Barrio == 'Chico Reservado'))

inmuebles_chico = (inmuebles.Barrio == 'Chico Reservado')
type(inmuebles_chico)

inmuebles.Area.mean()

chico_reservado = inmuebles[inmuebles.Barrio == 'Chico Reservado']
chico_reservado.Area.mean()

len(inmuebles.Barrio.value_counts())

len(inmuebles.UPZ.value_counts())

inmuebles_barrio = inmuebles.Barrio.value_counts()
inmuebles_barrio.plot.bar()

inmuebles_barrio = inmuebles.Barrio.value_counts()
inmuebles_barrio.plot.bar()

inmuebles_barrio.head(10).plot.bar()

promedio_area_por_barrio = inmuebles.groupby('Barrio')['Area'].mean().sort_values(ascending=False)
top_10_promedio_area_por_barrio = promedio_area_por_barrio.head(10)
print(top_10_promedio_area_por_barrio)

area_barrios = inmuebles.groupby('Barrio')['Area'].mean().sort_values(ascending=False).head(10)
print("Promedio de área de los inmuebles en los barrios (Top 10):\n", area_barrios)

stats_inmuebles = inmuebles.describe()
print("\nOtros datos estadísticos de los inmuebles:\n", stats_inmuebles)

count_inmuebles = inmuebles.count()
print("\nConteo de valores por columnas:\n", count_inmuebles)

print("\nValor máximo del precio:")
print(inmuebles['Valor'].max())

print("\nValor mínimo del precio:")
print(inmuebles['Valor'].min())
